import { ArrowDownLeft, ArrowUpRight, PiggyBank, Wallet } from 'lucide-react'
import { CashFlowChart } from '../../components/charts/CashFlowChart'
import { CategoryChart } from '../../components/charts/CategoryChart'
import { InsightCard } from '../../components/finance/InsightCard'
import { StatCard } from '../../components/finance/StatCard'
import { TransactionItem } from '../../components/finance/TransactionItem'
import { Card } from '../../components/ui/Card'
import { financialSummary, insights, transactions } from '../../data/mocks'

export function DashboardPage() {
  return <div className="space-y-6 lg:-mt-6"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Saldo do mês" value={financialSummary.balance} delta="↑ 14,2%" helper="em relação ao mês anterior" icon={Wallet} featured /><StatCard label="Receitas" value={financialSummary.income} delta="↑ 4,3%" helper="vs. média trimestral" icon={ArrowDownLeft} /><StatCard label="Despesas" value={financialSummary.expenses} delta="↓ 8,4%" helper="redução controlada" icon={ArrowUpRight} negative /><StatCard label="Taxa de poupança" value={financialSummary.savingsRate} format="percent" trailing="do total ganho" delta="↑ 6,2%" helper="R$ 2.340 economizados" icon={PiggyBank} /></section><section className="grid gap-4 xl:grid-cols-[minmax(0,2.1fr)_minmax(300px,1fr)]"><Card className="min-w-0 overflow-hidden p-6"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-border pb-5"><div><h2 className="text-[17px] font-semibold">Fluxo financeiro</h2><p className="mt-1 text-xs text-muted">Visão consolidada de entradas e saídas operacionais</p></div><div className="flex items-center gap-4 text-xs"><span className="flex items-center gap-2"><i className="size-2.5 rounded-full bg-primary" />Receitas</span><span className="flex items-center gap-2"><i className="size-2.5 rounded-full bg-muted" />Despesas</span><span className="rounded-control border border-border bg-surface-interactive px-3 py-2">Últimos 6 meses⌄</span></div></div><div className="min-w-0 pt-3"><CashFlowChart /></div><div className="flex items-center justify-between border-t border-border pt-4 text-[11px] text-muted"><span>◉ Superávit primário consecutivo há 6 meses</span><strong className="tabular text-primary">Margem livre: +R$ 2.340,50</strong></div></Card><Card className="min-w-0 overflow-hidden p-6"><div className="flex items-center justify-between border-b border-border pb-4"><h2 className="text-[17px] font-semibold">Gastos por categoria</h2><span className="text-[11px] font-semibold text-muted">SETEMBRO</span></div><CategoryChart /></Card></section><section className="grid gap-4 xl:grid-cols-[minmax(0,2.1fr)_minmax(300px,1fr)]"><Card className="min-h-[360px] p-6"><div className="mb-2 flex items-center justify-between"><div><h2 className="text-[17px] font-semibold">Transações recentes</h2><p className="mt-1 text-xs text-muted">Últimas movimentações registradas na conta</p></div><span className="text-xs font-medium text-primary">Ver todas →</span></div>{transactions.map((transaction) => <TransactionItem key={transaction.id} transaction={transaction} />)}</Card><InsightCard insight={insights[0]} /></section></div>
}
