import { ArrowDown, CalendarDays, ChartPie, CircleDollarSign, PiggyBank, Sparkles, TrendingUp, Utensils, WalletCards } from 'lucide-react'
import { useFinanceStore } from '../../app/store/useFinanceStore'
import { MonthlyInsightCard, type MonthlyInsightCardData } from '../../components/finance/MonthlyInsightCard'
import { Card } from '../../components/ui/Card'
import { Progress } from '../../components/ui/Progress'
import { getBudgetStatus } from '../../features/budgets/budget-status'
import { percentChange, periodKey, periodLabel, previousPeriod, selectCategorySpending, selectFinancialTotals, sumExpensesForCategory } from '../../features/analytics/finance-selectors'
import { formatCurrency } from '../../lib/formatters'

export function InsightsPage() {
  const { transactions, categories, budgets, activePeriod, summary } = useFinanceStore()
  const priorPeriod = previousPeriod(activePeriod)
  const prior = selectFinancialTotals(transactions, priorPeriod)
  const ranking = selectCategorySpending(transactions, categories, activePeriod)
  const priorRanking = selectCategorySpending(transactions, categories, priorPeriod)
  const expenseChange = percentChange(summary.expenses, prior.expenses)
  const incomeChange = percentChange(summary.income, prior.income)
  const balanceChange = percentChange(summary.balance, prior.balance)
  const savingDelta = prior.income > 0 ? summary.savingsRate - prior.savingsRate : null
  const hasPriorData = prior.income > 0 || prior.expenses > 0
  const cards = buildCards(ranking, priorRanking, budgets.filter((budget) => budget.month === periodKey(activePeriod)).map((budget) => ({ ...budget, spent: sumExpensesForCategory(transactions, budget.categoryId, activePeriod), name: categories.find((category) => category.id === budget.categoryId)?.name ?? 'Sem categoria' })), savingDelta)
  const headline = !hasPriorData ? 'Ainda não há dados suficientes para comparar os meses.' : expenseChange !== null && expenseChange <= 0 ? 'Você está gastando menos que no mês anterior.' : 'Suas despesas aumentaram em relação ao mês anterior.'

  return <div className="mx-auto max-w-[1440px] space-y-6">
    <header className="flex items-start justify-between gap-5"><div><div className="flex items-center gap-2"><h1 className="text-[28px] font-semibold tracking-tight">GO Insights</h1><span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-primary">Inteligência Financeira</span></div><p className="mt-1 text-sm text-muted">Entenda o que está acontecendo com suas finanças de forma transparente e objetiva.</p></div><button className="focus-ring flex h-10 shrink-0 items-center gap-2 rounded-control border border-border bg-surface px-3 text-xs"><CalendarDays size={16} className="text-muted" />{periodLabel(activePeriod)}<span className="text-muted">⌄</span></button></header>

    <section className="relative overflow-hidden rounded-card border border-border bg-surface p-8"><div className="pointer-events-none absolute -right-24 -top-24 size-80 rounded-full bg-primary/5 blur-3xl" /><div className="relative flex items-center justify-between gap-8"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full bg-surface-interactive px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wide"><Sparkles size={13} className="text-primary" />Resumo de {periodLabel(activePeriod, 'short')}</span><h2 className="mt-4 text-[28px] font-semibold tracking-tight">{headline}</h2><p className="mt-1 text-[15px] leading-6 text-muted">Despesas de <strong className="font-medium text-primary">{formatCurrency(summary.expenses)}</strong> e taxa de economia de <strong className="font-medium text-primary">{formatPercent(summary.savingsRate)}</strong>. {hasPriorData ? `Comparação baseada nos dados de ${periodLabel(priorPeriod)}.` : 'Novas transações tornarão a análise comparativa disponível.'}</p></div><div className="grid shrink-0 grid-cols-2 gap-3"><Highlight label="Nas despesas" value={change(expenseChange)} helper={hasPriorData ? `vs. ${periodLabel(priorPeriod, 'short')}` : 'Sem base anterior'} down={expenseChange !== null && expenseChange < 0} /><Highlight label="De economia" value={formatPercent(summary.savingsRate)} helper={`${formatCurrency(summary.balance)} no período`} /></div></div></section>

    <section className="grid grid-cols-3 gap-4"><Metric label="Despesas" value={formatCurrency(summary.expenses)} changeValue={change(expenseChange)} /><Metric label="Economia" value={formatCurrency(summary.balance)} changeValue={change(balanceChange)} /><Metric label="Taxa de economia" value={formatPercent(summary.savingsRate)} changeValue={savingDelta === null ? 'Sem comparação' : `${signed(savingDelta)} p.p.`} /></section>

    <section><h2 className="text-xl font-semibold">Principais insights</h2><p className="mt-0.5 text-[11px] text-muted">Regras determinísticas calculadas a partir das transações atuais.</p><div className="mt-4 grid grid-cols-3 gap-4">{cards.map((insight) => <MonthlyInsightCard key={insight.id} insight={insight} />)}</div></section>

    <section className="grid grid-cols-12 items-start gap-6"><Card className="col-span-7 p-6"><div className="flex items-start justify-between"><div><h2 className="text-xl font-semibold">Onde seu dinheiro foi</h2><p className="mt-1 text-[11px] text-muted">Ranking das principais categorias do mês</p></div><span className="tabular text-sm text-muted">{formatCurrency(summary.expenses)} Total</span></div><div className="mt-6 space-y-4">{ranking.length ? ranking.slice(0, 5).map((category, index) => <div key={category.id}><div className="mb-2 flex items-center justify-between text-xs"><div className="flex items-center gap-3"><span className="tabular w-4 text-muted">{String(index + 1).padStart(2, '0')}</span><strong className="font-medium">{category.name}</strong></div><div className="tabular flex items-center gap-6"><span>{formatCurrency(category.amount)}</span><span className={index === 0 ? 'w-9 text-right text-primary' : 'w-9 text-right text-muted'}>{category.percentage.toFixed(0)}%</span></div></div><Progress value={category.percentage} /></div>) : <p className="text-sm text-muted">Nenhuma despesa registrada no período.</p>}</div></Card><div className="col-span-5 space-y-4"><Card className="p-6"><div className="flex items-center justify-between"><h2 className="text-base font-semibold">Comparação com {periodLabel(priorPeriod, 'short')}</h2><span className="text-[10px] font-semibold uppercase tracking-wide text-muted">Dados calculados</span></div><div className="mt-4 divide-y divide-border"><Comparison label="Receitas" value={change(incomeChange)} /><Comparison label="Despesas" value={change(expenseChange)} /><Comparison label="Economia" value={change(balanceChange)} /></div></Card><Card className="p-6"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-control bg-primary/10 text-primary"><TrendingUp size={18} /></span><h2 className="text-base font-semibold">Leitura do período</h2></div><p className="mt-4 text-xs leading-5 text-muted">{hasPriorData ? headline : 'A comparação será exibida assim que houver transações no mês anterior.'}</p><p className="mt-4 flex items-center gap-2 text-[11px] font-medium text-primary"><i className="size-2 rounded-full bg-primary" />Análise rule-based atualizada em tempo real</p></Card></div></section>
  </div>
}

function buildCards(current: ReturnType<typeof selectCategorySpending>, prior: ReturnType<typeof selectCategorySpending>, budgets: Array<{ id: string; name: string; limit: number; spent: number; alertAt: number }>, savingDelta: number | null): MonthlyInsightCardData[] {
  const categoryCards = current.slice(0, 3).map((category, index) => {
    const old = prior.find((item) => item.id === category.id)?.amount ?? 0
    const delta = percentChange(category.amount, old)
    const direction = delta === null ? 'neutral' : delta > 0 ? 'warning' : 'positive'
    return { id: `category-${category.id}`, category: category.name, icon: index === 0 ? Utensils : ChartPie, tone: direction, status: delta === null ? `${category.percentage.toFixed(0)}% do total` : change(delta), title: delta === null ? `${category.name} está entre seus maiores gastos.` : `${category.name} ${delta > 0 ? 'aumentou' : 'diminuiu'} no período.`, description: delta === null ? 'Não há base anterior suficiente para calcular a variação.' : `Comparação com o mesmo agrupamento do mês anterior.`, meta: `${formatCurrency(category.amount)} no mês atual`, progress: Math.min(100, category.percentage) } satisfies MonthlyInsightCardData
  })
  const budgetCards = budgets.filter((budget) => getBudgetStatus(Math.round((budget.spent / budget.limit) * 100), budget.alertAt) !== 'primary').slice(0, 2).map((budget) => {
    const percentage = Math.round((budget.spent / budget.limit) * 100)
    const exceeded = percentage > 100
    return { id: `budget-${budget.id}`, category: 'Orçamentos', icon: WalletCards, tone: exceeded ? 'danger' : 'warning', status: `${percentage}% usado`, title: `${budget.name} ${exceeded ? 'ultrapassou' : 'está próximo de'} seu limite.`, description: `${formatCurrency(budget.spent)} gastos de um limite de ${formatCurrency(budget.limit)}.`, progress: Math.min(100, percentage) } satisfies MonthlyInsightCardData
  })
  const savingCard: MonthlyInsightCardData = { id: 'saving-rate', category: 'Economia', icon: PiggyBank, tone: savingDelta === null ? 'neutral' : savingDelta >= 0 ? 'positive' : 'warning', status: savingDelta === null ? 'Sem comparação' : `${signed(savingDelta)} p.p.`, title: savingDelta === null ? 'Taxa de economia sem base anterior.' : `Sua taxa de economia ${savingDelta >= 0 ? 'melhorou' : 'piorou'}.`, description: savingDelta === null ? 'Registre receitas e despesas no mês anterior para habilitar esta leitura.' : 'Comparação entre a parcela economizada da renda nos dois períodos.' }
  return [...categoryCards, ...budgetCards, savingCard]
}

function Highlight({ label, value, helper, down }: { label: string; value: string; helper: string; down?: boolean }) { const Icon = down ? ArrowDown : TrendingUp; return <div className="min-w-40 rounded-card bg-surface-interactive p-5"><p className="text-[11px] font-semibold uppercase tracking-wide text-muted">{label}</p><p className="mt-1 flex items-center gap-1 text-2xl font-semibold text-primary"><Icon size={20} /><span className="tabular">{value}</span></p><p className="tabular mt-1 text-[10px] text-muted">{helper}</p></div> }
function Metric({ label, value, changeValue }: { label: string; value: string; changeValue: string }) { return <Card className="flex min-h-36 flex-col justify-between p-5"><div className="flex items-center justify-between"><span className="text-[11px] font-semibold uppercase tracking-wide text-muted">{label}</span><span className="grid size-9 place-items-center rounded-control bg-surface-interactive text-muted"><CircleDollarSign size={17} /></span></div><div><strong className="tabular text-2xl font-semibold">{value}</strong><p className="mt-2 text-[11px] text-primary">{changeValue} <span className="text-muted">vs. mês anterior</span></p></div></Card> }
function Comparison({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between py-3 first:pt-0 last:pb-0"><span className="flex items-center gap-2 text-xs"><i className="size-2 rounded-full bg-primary" />{label}</span><span className="tabular rounded-full bg-primary/10 px-2 py-1 text-[11px] font-medium text-primary">{value}</span></div> }
function change(value: number | null) { return value === null ? 'Sem comparação' : `${signed(value)}%` }
function signed(value: number) { return `${value >= 0 ? '+' : ''}${value.toFixed(1).replace('.', ',')}` }
function formatPercent(value: number) { return `${value.toFixed(1).replace('.', ',')}%` }
