import { useMemo, useState } from 'react'
import {
  AlertTriangle, BadgeCheck, Banknote, BriefcaseBusiness, CalendarDays, Car, Check, CircleDollarSign,
  Download, Gamepad2, GraduationCap, HeartPulse, House, Landmark, Moon, Pencil, Plus, Save,
  Shapes, ShoppingBag, Trash2, TrendingUp, Utensils, WalletCards,
} from 'lucide-react'
import { SettingsModal } from '../../components/settings/SettingsModal'
import { Button } from '../../components/ui/Button'
import { Card } from '../../components/ui/Card'
import { Input } from '../../components/ui/Input'
import { Select } from '../../components/ui/Select'
import { paymentMethodMocks, preferenceMocks, profileSettings, settingsCategoryMocks, type PaymentMethod, type PaymentMethodKind, type SettingsCategory, type SettingsCategoryType } from '../../data/mocks/settings'
import { transactions } from '../../data/mocks/transactions'

type ModalState = { type: 'payment'; item?: PaymentMethod } | { type: 'category'; item?: SettingsCategory } | { type: 'delete-payment'; item: PaymentMethod } | { type: 'delete-category'; item: SettingsCategory } | { type: 'danger' } | null

const categoryIcons = { utensils: Utensils, car: Car, house: House, heart: HeartPulse, graduation: GraduationCap, gamepad: Gamepad2, calendar: CalendarDays, shopping: ShoppingBag, shapes: Shapes, wallet: WalletCards, briefcase: BriefcaseBusiness, trending: TrendingUp, 'circle-dollar': CircleDollarSign }
const iconOptions = Object.keys(categoryIcons)

function SectionTitle({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) {
  return <div className="flex items-start justify-between gap-4 border-b border-border pb-4"><div><h2 className="text-base font-semibold">{title}</h2><p className="mt-1 text-[11px] text-muted">{description}</p></div>{action}</div>
}

export function SettingsPage() {
  const [profile, setProfile] = useState(profileSettings)
  const [savedProfile, setSavedProfile] = useState(profileSettings)
  const [paymentMethods, setPaymentMethods] = useState(paymentMethodMocks)
  const [categories, setCategories] = useState(settingsCategoryMocks)
  const [categoryType, setCategoryType] = useState<SettingsCategoryType>('expense')
  const [preferences, setPreferences] = useState(preferenceMocks)
  const [modal, setModal] = useState<ModalState>(null)
  const [formName, setFormName] = useState('')
  const [formDescription, setFormDescription] = useState('')
  const [paymentKind, setPaymentKind] = useState<PaymentMethodKind>('Conta digital')
  const [categoryIcon, setCategoryIcon] = useState('shapes')
  const [feedback, setFeedback] = useState('Alterações locais prontas')

  const visibleCategories = useMemo(() => categories.filter((category) => category.type === categoryType), [categories, categoryType])

  function openPayment(item?: PaymentMethod) { setFormName(item?.name ?? ''); setFormDescription(item?.description ?? ''); setPaymentKind(item?.kind ?? 'Conta digital'); setModal({ type: 'payment', item }) }
  function openCategory(item?: SettingsCategory) { setFormName(item?.name ?? ''); setCategoryIcon(item?.icon ?? 'shapes'); setModal({ type: 'category', item }) }
  function closeModal() { setModal(null); setFormName(''); setFormDescription('') }
  function savePayment() {
    const name = formName.trim(); if (!name) return
    if (modal?.type === 'payment' && modal.item) setPaymentMethods((items) => items.map((item) => item.id === modal.item?.id ? { ...item, name, kind: paymentKind, description: formDescription.trim() || paymentKind } : item))
    else setPaymentMethods((items) => [...items, { id: `payment-${Date.now()}`, name, kind: paymentKind, description: formDescription.trim() || paymentKind, color: '#22c55e' }])
    setFeedback(modal?.type === 'payment' && modal.item ? 'Forma de pagamento atualizada' : 'Forma de pagamento adicionada'); closeModal()
  }
  function saveCategory() {
    const name = formName.trim(); if (!name) return
    if (modal?.type === 'category' && modal.item) setCategories((items) => items.map((item) => item.id === modal.item?.id ? { ...item, name, icon: categoryIcon } : item))
    else setCategories((items) => [...items, { id: `category-${Date.now()}`, name, type: categoryType, icon: categoryIcon, color: categoryType === 'income' ? '#22c55e' : '#fbbf24' }])
    setFeedback(modal?.type === 'category' && modal.item ? 'Categoria atualizada' : 'Categoria adicionada'); closeModal()
  }
  function exportCsv() {
    const header = ['Descrição', 'Valor', 'Tipo', 'Data', 'Categoria', 'Forma de pagamento']
    const rows = transactions.map((transaction) => [transaction.description, transaction.amount.toFixed(2), transaction.kind, transaction.date, transaction.categoryId, transaction.accountId])
    const csv = [header, ...rows].map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n')
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }))
    const link = document.createElement('a'); link.href = url; link.download = 'go-finance-transacoes.csv'; link.click(); URL.revokeObjectURL(url)
    setFeedback('CSV exportado localmente')
  }

  return <div className="mx-auto max-w-[1440px] space-y-6">
    <header className="flex items-end justify-between gap-6"><div><p className="text-[11px] font-semibold uppercase tracking-[.06em] text-primary">Sistema • Governança</p><h1 className="mt-1 text-[28px] font-semibold tracking-tight">Configurações</h1><p className="mt-1 text-sm text-muted">Personalize sua experiência operacional e fiscal no GO Finance.</p></div><div className="flex items-center gap-2 rounded-control border border-border bg-surface px-3 py-2 text-[11px] text-muted"><i className="size-2 rounded-full bg-primary" />{feedback}</div></header>
    <nav aria-label="Seções de configuração" className="flex gap-1 border-b border-border pb-1 text-xs"><a href="#geral" className="rounded-control bg-surface-interactive px-3 py-2 font-semibold text-text">Geral</a><a href="#payments" className="rounded-control px-3 py-2 text-muted hover:bg-surface">Contas e Pagamentos</a><a href="#categories" className="rounded-control px-3 py-2 text-muted hover:bg-surface">Categorias</a><a href="#preferences" className="rounded-control px-3 py-2 text-muted hover:bg-surface">Preferências</a><a href="#data" className="rounded-control px-3 py-2 text-muted hover:bg-surface">Dados e Segurança</a></nav>

    <div className="grid grid-cols-12 items-start gap-6">
      <div className="col-span-5 space-y-6">
        <Card id="geral" className="p-5"><SectionTitle title="Perfil" description="Gerencie seus dados de identificação e credenciais." action={<BadgeCheck size={19} className="text-muted" />} /><div className="my-4 flex items-center gap-3 rounded-control bg-surface-interactive p-3"><span className="relative grid size-14 shrink-0 place-items-center rounded-full border-2 border-primary/40 bg-gradient-to-br from-slate-600 to-slate-900 text-sm font-semibold">{profile.initials}<i className="absolute bottom-0 right-0 size-3 rounded-full bg-primary ring-2 ring-surface-interactive" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{savedProfile.name}<span className="ml-2 rounded border border-primary/20 bg-primary/10 px-1 py-0.5 text-[9px] text-primary">LOCAL</span></p><p className="mt-1 text-[11px] text-muted">Conta pessoal primária</p></div></div><form onSubmit={(event) => { event.preventDefault(); setSavedProfile(profile); setFeedback('Perfil salvo localmente') }} className="space-y-4"><label className="block text-[10px] font-semibold uppercase tracking-wide text-muted">Nome completo<Input aria-label="Nome completo" className="mt-1" value={profile.name} onChange={(event) => setProfile({ ...profile, name: event.target.value, initials: event.target.value.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase() })} /></label><label className="block text-[10px] font-semibold uppercase tracking-wide text-muted">E-mail corporativo / pessoal<Input aria-label="E-mail" className="mt-1" type="email" value={profile.email} onChange={(event) => setProfile({ ...profile, email: event.target.value })} /></label><div className="flex items-center justify-between"><span className="text-[10px] text-muted">Os dados ficam somente nesta sessão.</span><Button type="submit" className="h-9 text-xs"><Save size={14} />Salvar alterações</Button></div></form></Card>

        <Card id="preferences" className="p-5"><SectionTitle title="Preferências Gerais" description="Formatação, período fiscal e padrões visuais." /><div className="divide-y divide-border"><label className="flex items-center justify-between gap-4 py-4"><span><strong className="block text-xs font-medium">Moeda padrão</strong><small className="text-[10px] text-muted">Base para valores do aplicativo</small></span><Select aria-label="Moeda padrão" className="h-9 w-48 text-xs" value={preferences.currency} onChange={(event) => setPreferences({ ...preferences, currency: event.target.value })}><option value="BRL">R$ — Real brasileiro</option><option value="USD">$ — Dólar americano</option><option value="EUR">€ — Euro</option></Select></label><div className="flex items-center justify-between py-4"><span><strong className="block text-xs font-medium">Formato de data</strong><small className="text-[10px] text-muted">Visualização em extratos</small></span><span className="tabular rounded border border-border bg-surface-interactive px-3 py-2 text-xs">DD/MM/AAAA</span></div><label className="flex items-center justify-between gap-4 py-4"><span><strong className="block text-xs font-medium">Primeiro dia do mês fiscal</strong><small className="text-[10px] text-muted">Início do cálculo de orçamentos</small></span><Select aria-label="Primeiro dia do mês fiscal" className="h-9 w-36 text-xs" value={preferences.fiscalDay} onChange={(event) => setPreferences({ ...preferences, fiscalDay: event.target.value })}><option value="1">Dia 1</option><option value="5">Dia 5</option><option value="10">Dia 10</option><option value="25">Dia 25</option></Select></label><div className="flex items-center justify-between pt-4"><span><strong className="block text-xs font-medium">Aparência da interface</strong><small className="text-[10px] text-muted">Tema otimizado para baixa reflexividade</small></span><span className="inline-flex items-center gap-2 rounded border border-border bg-surface-interactive px-3 py-2 text-xs"><Moon size={14} className="text-primary" />Tema escuro</span></div></div></Card>

        <Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold">Alertas de Orçamento</h2><p className="mt-1 text-[11px] text-muted">Avisos locais preventivos de estouro de teto.</p></div><button role="switch" aria-checked={preferences.budgetAlerts} aria-label="Alertas de orçamento" onClick={() => setPreferences({ ...preferences, budgetAlerts: !preferences.budgetAlerts })} className={`relative h-6 w-11 rounded-full transition ${preferences.budgetAlerts ? 'bg-primary' : 'bg-border-strong'}`}><span className={`absolute top-1 size-4 rounded-full bg-white transition-all ${preferences.budgetAlerts ? 'left-6' : 'left-1'}`} /></button></div><div className="mt-4 rounded-control border border-border bg-surface-interactive p-3"><div className="flex justify-between text-[11px]"><span className="text-muted">Sensibilidade do alerta</span><strong className="text-primary">80% do teto</strong></div><div className="mt-3 h-1.5 rounded-full bg-border-strong"><div className="h-full w-4/5 rounded-full bg-primary" /></div><p className="mt-3 text-[10px] leading-4 text-muted">Avisos aparecem apenas na interface. Nenhuma notificação externa é enviada.</p></div></Card>
      </div>

      <div className="col-span-7 space-y-6">
        <Card id="payments" className="p-5"><SectionTitle title="Contas e Pagamentos" description="Classificações de origem e formas de pagamento — sem saldos." action={<Button variant="secondary" className="h-8 px-3 text-xs" onClick={() => openPayment()}><Plus size={14} />Nova conta</Button>} /><div className="mt-3 divide-y divide-border">{paymentMethods.map((method) => <div key={method.id} className="flex items-center justify-between py-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-control border" style={{ color: method.color, borderColor: `${method.color}66`, backgroundColor: `${method.color}18` }}>{method.kind === 'Dinheiro' ? <Banknote size={18} /> : <Landmark size={18} />}</span><div><p className="text-xs font-medium">{method.name}</p><p className="mt-1 text-[10px] text-muted">{method.kind} • {method.description}</p></div></div><div className="flex gap-1"><button aria-label={`Editar ${method.name}`} className="focus-ring grid size-8 place-items-center rounded text-muted hover:bg-surface-interactive hover:text-text" onClick={() => openPayment(method)}><Pencil size={15} /></button><button aria-label={`Excluir ${method.name}`} className="focus-ring grid size-8 place-items-center rounded text-muted hover:bg-danger/10 hover:text-danger" onClick={() => setModal({ type: 'delete-payment', item: method })}><Trash2 size={15} /></button></div></div>)}</div></Card>

        <Card id="categories" className="p-5"><SectionTitle title="Categorias" description="Classificação de receitas e despesas por nome, ícone e tipo." action={<Button variant="secondary" className="h-8 px-3 text-xs" onClick={() => openCategory()}><Plus size={14} />Nova categoria</Button>} /><div className="mt-4 inline-flex rounded-control border border-border bg-canvas p-1 text-[11px]"><button className={`rounded px-3 py-1.5 ${categoryType === 'expense' ? 'bg-surface-interactive font-semibold' : 'text-muted'}`} onClick={() => setCategoryType('expense')}>Despesas ({categories.filter((item) => item.type === 'expense').length})</button><button className={`rounded px-3 py-1.5 ${categoryType === 'income' ? 'bg-surface-interactive font-semibold' : 'text-muted'}`} onClick={() => setCategoryType('income')}>Receitas ({categories.filter((item) => item.type === 'income').length})</button></div><div className="mt-4 grid grid-cols-3 gap-2">{visibleCategories.map((category) => { const Icon = categoryIcons[category.icon as keyof typeof categoryIcons] ?? Shapes; return <div key={category.id} className="flex items-center justify-between rounded-control border border-border bg-surface-interactive p-2.5"><span className="flex min-w-0 items-center gap-2 text-[11px] font-medium"><Icon size={16} style={{ color: category.color }} /><span className="truncate">{category.name}</span></span><span className="flex"><button aria-label={`Editar categoria ${category.name}`} className="p-1 text-muted hover:text-text" onClick={() => openCategory(category)}><Pencil size={12} /></button><button aria-label={`Excluir categoria ${category.name}`} className="p-1 text-muted hover:text-danger" onClick={() => setModal({ type: 'delete-category', item: category })}><Trash2 size={12} /></button></span></div> })}</div></Card>

        <Card id="data" className="p-5"><SectionTitle title="Dados do Sistema & Portabilidade" description="Exporte uma cópia local ou simule a limpeza dos dados." /><div className="mt-4 space-y-3"><div className="flex items-center justify-between rounded-control border border-border bg-surface-interactive p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded bg-border text-primary"><Download size={17} /></span><div><p className="text-xs font-medium">Exportar transações financeiras</p><p className="mt-1 text-[10px] text-muted">Arquivo CSV gerado localmente com os dados mockados</p></div></div><Button variant="secondary" className="h-8 text-xs" onClick={exportCsv}>Exportar CSV</Button></div><div className="flex items-center justify-between rounded-control border border-danger/30 bg-danger/10 p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded bg-danger/10 text-danger"><AlertTriangle size={17} /></span><div><p className="text-xs font-medium text-danger">Área de perigo: Excluir todos os dados</p><p className="mt-1 text-[10px] text-muted">Simulação segura — nenhuma conta ou dado real será excluído</p></div></div><Button className="h-8 border-danger/30 bg-danger/10 text-xs text-danger hover:bg-danger/20" onClick={() => setModal({ type: 'danger' })}>Excluir dados</Button></div></div></Card>
      </div>
    </div>

    <SettingsModal open={modal?.type === 'payment'} title={modal?.type === 'payment' && modal.item ? 'Editar forma de pagamento' : 'Nova forma de pagamento'} eyebrow="Classificação • V1" description="Use apenas para identificar a origem da transação. Nenhum saldo é calculado." onClose={closeModal} footer={<><Button variant="ghost" onClick={closeModal}>Cancelar</Button><Button disabled={!formName.trim()} onClick={savePayment}>{modal?.type === 'payment' && modal.item ? 'Salvar' : 'Adicionar'}</Button></>}><div className="space-y-4"><label className="block text-[10px] font-semibold uppercase tracking-wide text-muted">Nome<Input autoFocus aria-label="Nome da forma de pagamento" className="mt-1" placeholder="Ex: Cartão Inter" value={formName} onChange={(event) => setFormName(event.target.value)} /></label><label className="block text-[10px] font-semibold uppercase tracking-wide text-muted">Tipo<Select aria-label="Tipo da forma de pagamento" className="mt-1" value={paymentKind} onChange={(event) => setPaymentKind(event.target.value as PaymentMethodKind)}><option>Conta digital</option><option>Conta corrente</option><option>Dinheiro</option><option>Outro</option></Select></label><label className="block text-[10px] font-semibold uppercase tracking-wide text-muted">Descrição<Input aria-label="Descrição da forma de pagamento" className="mt-1" placeholder="Uso desta forma de pagamento" value={formDescription} onChange={(event) => setFormDescription(event.target.value)} /></label></div></SettingsModal>

    <SettingsModal open={modal?.type === 'category'} title={modal?.type === 'category' && modal.item ? 'Editar categoria' : 'Nova categoria'} eyebrow={categoryType === 'expense' ? 'Categoria • Despesa' : 'Categoria • Receita'} onClose={closeModal} footer={<><Button variant="ghost" onClick={closeModal}>Cancelar</Button><Button disabled={!formName.trim()} onClick={saveCategory}>{modal?.type === 'category' && modal.item ? 'Salvar' : 'Adicionar'}</Button></>}><div className="space-y-4"><label className="block text-[10px] font-semibold uppercase tracking-wide text-muted">Nome<Input autoFocus aria-label="Nome da categoria" className="mt-1" value={formName} onChange={(event) => setFormName(event.target.value)} /></label><label className="block text-[10px] font-semibold uppercase tracking-wide text-muted">Ícone<Select aria-label="Ícone da categoria" className="mt-1" value={categoryIcon} onChange={(event) => setCategoryIcon(event.target.value)}>{iconOptions.map((icon) => <option key={icon} value={icon}>{icon}</option>)}</Select></label><p className="rounded-control border border-border bg-surface-interactive p-3 text-xs text-muted">Tipo: <strong className="text-text">{modal?.type === 'category' && modal.item ? (modal.item.type === 'expense' ? 'Despesa' : 'Receita') : (categoryType === 'expense' ? 'Despesa' : 'Receita')}</strong></p></div></SettingsModal>

    <SettingsModal open={modal?.type === 'delete-payment' || modal?.type === 'delete-category'} title="Confirmar exclusão local" eyebrow="Ação reversível ao recarregar" description="Este item será removido apenas do estado desta sessão." onClose={closeModal} footer={<><Button variant="ghost" onClick={closeModal}>Cancelar</Button><Button className="border-danger/30 bg-danger/10 text-danger hover:bg-danger/20" onClick={() => { if (modal?.type === 'delete-payment') setPaymentMethods((items) => items.filter((item) => item.id !== modal.item.id)); if (modal?.type === 'delete-category') setCategories((items) => items.filter((item) => item.id !== modal.item.id)); setFeedback('Item excluído localmente'); closeModal() }}><Trash2 size={15} />Excluir</Button></>}><p className="text-sm text-muted">Deseja excluir <strong className="text-text">{modal?.type === 'delete-payment' || modal?.type === 'delete-category' ? modal.item.name : ''}</strong>?</p></SettingsModal>

    <SettingsModal open={modal?.type === 'danger'} title="Simular exclusão de dados?" eyebrow="Área de perigo" description="Não há backend nesta versão. A confirmação não apaga conta, arquivos ou dados reais." onClose={closeModal} footer={<><Button variant="ghost" onClick={closeModal}>Cancelar</Button><Button className="border-danger/30 bg-danger/10 text-danger hover:bg-danger/20" onClick={() => { setFeedback('Simulação concluída — nenhum dado real foi excluído'); closeModal() }}><Check size={15} />Confirmar simulação</Button></>}><div className="rounded-control border border-danger/20 bg-danger/10 p-4 text-xs leading-5 text-muted">Esta ação serve apenas para validar o fluxo visual da V1. Todos os mocks permanecem intactos.</div></SettingsModal>
  </div>
}
